### ISSUE TITLE
Switch bullet type when we indent with TAB

### ISSUE THREAD

**Issue by dorian-marchal** [brunobord/markdown-lists#2]
Is this complicated to add something like that ?

![deep](https://cloud.githubusercontent.com/assets/6225979/7468806/18765152-f30d-11e4-81ff-b14a7ced22bb.gif)

This would be super useful :)

**Comment by brunobord** [comment]
I have no idea... :o) will try to have a look.

**Comment by jronallo** [comment]
As I write a lot of Markdown lists tab to indent for a nested list is the single biggest feature that leaves me frustrated with atom after switching from sublime.

**Comment by ssergiienko** [comment]
https://atom.io/packages/markdown-writer already has such functionality, maybe some copy/paste would be enough? :)
